const message = {
    login:{
        username:'username',
        password:'password',
        lang:'language'
    },
    Header:{
        tittle:'Container Internet of things platform',
        per:'Profile',
        change:'Change password',
        logo:'Logout'
    },
    Sidebar:{
        home:'Home',
        frige:'Frige',
        location:'Location',
        list:'List',
        group:'Grouping',
        moni:'Monitoring',
        box:'Container',
        refrigerator:'Refrigerator',
        door:'Container door',
        trend:'Fresh air',
        duration:'Duration',
        alarm:'Alarm',
        real:'Real Time',
        travel:'Travel',
        detail:'Detail',
        add:'Add',
        log:'Log',
        user:'User',
        control:'Control',
    },
    index:{
        list:'Container',
        full:'Full container',
        on:'On-line',
        off:'Off-line',
        alarm:'Alarm',
        con:'Container',
        temp:'Temp°C',
        humi:'Humi%',
        cooler:'Cooler mode',
        cooler_voltage:'Cooler voltage',
        time:'Update time',
        settemp:'Set temp',
        retemp:'Return air temp°C',
        outtemp:'Air outlet temp°C',
        ambient:'Ambient temp°C',
        dep:'Deputy voltage',
        cur:'Cooler Current',
        water:'Water temp°C',
        suc:'Suction pressure',
        ex:'Exhaust pressure',
        address:'address',
        oil:'oil_temp',
        zone:'State Information effectiveness',
        state:'State Information',
        soft:'Software version',
        run:'Power running time(h)',
        work:'Work hour(h)',
        Alarmcode:'Alarm code',
        temp1:'Temp 1',
        temp2:'Temp 2',
        temp3:'Temp 3',
        Averagetemp:'Average temp',
        level:'Oil level',
        speed:'Speed',
        dir:'Direaction',
        lat:'Longitude and Latitude',
        door:'Door',
        Cooler:'Cooler',
        Sensor:'Sensor',
        Command:'Command',
        Container:'Container',
        DTU:'DTU',
        CoolerOpen:'Cooler Open',
        start:'Start',
        stop:'Stop',
        Currentoption:' Current option',
        time:'time',
        set:'Set',
        Clearalarm:'Clear alarm',
        Clear:' Clear',
        Defrost:'Defrost',
        init:'Initialization defrosting',
        mode:'Workong mode',
        contin:'Continuous mode',
        cycle:'Cycle mode',
        airdoor:'Fresh air door',
        setfte:'set'
    }
}
export default message;